# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - test-d-02-apps

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://sampleappaoaichatgpt.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_c09e4e0fbe154d91a4807d5c44aa07c0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b998208143b4953acae9edbff431c9f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c09e4e0fbe154d91a4807d5c44aa07c0 }}/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'test-d-02-apps'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a40aa3cfabd242de98fb6b01d8e3da15 }}
        images: 'sampleappaoaichatgpt.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c09e4e0fbe154d91a4807d5c44aa07c0 }}/sample-app-aoai-chatgpt:${{ github.sha }}'